/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package WindowsFrame;


/**
 *
 * @author Rodion
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameProgramm = new javax.swing.JLabel();
        ButtonConfirm = new javax.swing.JButton();
        ButtonExit = new javax.swing.JButton();
        GeneratedKey = new javax.swing.JLabel();
        LengthKey = new javax.swing.JLabel();
        ComplicatedKey = new javax.swing.JLabel();
        enterLegthKey = new javax.swing.JTextField();
        enterComplicatedKey = new javax.swing.JTextField();
        ThisIsGenerateKey = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        StartGenerate = new javax.swing.JButton();
        Line = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        EnterLine = new javax.swing.JTextField();
        output_encoding_Base64 = new javax.swing.JTextField();
        output_encrypt_sha1 = new javax.swing.JTextField();
        output_encrypt_md5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        output_ecodingBase64_sha1 = new javax.swing.JTextField();
        output_encodingBase64_md5 = new javax.swing.JTextField();
        ButtonReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameProgramm.setText("ПРОГРАММА ШИФРОВАНИЯ");

        ButtonConfirm.setText("Подтвердить");
        ButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConfirmActionPerformed(evt);
            }
        });

        ButtonExit.setText("Выход");
        ButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonExitActionPerformed(evt);
            }
        });

        GeneratedKey.setText("ГЕНЕРИРОВАНИЕ КЛЮЧА");

        LengthKey.setText("Длина ключа");

        ComplicatedKey.setText("Уровень сложности(1-4)");

        enterLegthKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterLegthKeyActionPerformed(evt);
            }
        });

        enterComplicatedKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterComplicatedKeyActionPerformed(evt);
            }
        });

        jLabel1.setText("Сгенерированный ключ");

        StartGenerate.setText("Сгенерировать");
        StartGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartGenerateActionPerformed(evt);
            }
        });

        Line.setText("Получение строки");

        jLabel3.setText("Кодировка по BASE64");

        jLabel4.setText("Шифрование по SHA-1");

        jLabel5.setText("Шифрование по MD5");

        jLabel6.setText("Кодирование шифра по BASE64 (SHA-1)");

        jLabel7.setText("Кодирование шифра по BASE64 (MD5)");

        ButtonReset.setText("Сбросить");
        ButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(226, 226, 226)
                                .addComponent(GeneratedKey))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addComponent(nameProgramm))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(output_encodingBase64_md5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(output_ecodingBase64_sha1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(output_encrypt_md5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(output_encoding_Base64, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ButtonReset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonConfirm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(LengthKey)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enterLegthKey, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(ComplicatedKey)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(enterComplicatedKey, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                                .addComponent(StartGenerate)
                                .addGap(11, 11, 11))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(Line))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ThisIsGenerateKey))
                            .addComponent(EnterLine)
                            .addComponent(output_encrypt_sha1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GeneratedKey)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LengthKey)
                    .addComponent(enterLegthKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComplicatedKey)
                    .addComponent(enterComplicatedKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartGenerate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ThisIsGenerateKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(nameProgramm)
                .addGap(22, 22, 22)
                .addComponent(Line)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EnterLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(output_encoding_Base64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(output_encrypt_sha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(output_encrypt_md5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(output_ecodingBase64_sha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(output_encodingBase64_md5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonConfirm)
                    .addComponent(ButtonExit)
                    .addComponent(ButtonReset))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterLegthKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterLegthKeyActionPerformed
       //String lengthKey = enterLegthKey.getText();
    }//GEN-LAST:event_enterLegthKeyActionPerformed

    private void enterComplicatedKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterComplicatedKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterComplicatedKeyActionPerformed

    private void StartGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartGenerateActionPerformed
        String lengthKey = enterLegthKey.getText();
        String complicatedKey = enterComplicatedKey.getText();
        
            Integer intlengthKey = 0;
            Integer intcomplicatedKey = 0;
            try { 
                intlengthKey = new Integer(lengthKey);
                intcomplicatedKey = new Integer(complicatedKey);
            }catch (NumberFormatException e) {  
                System.err.println("Неверный формат строки!");  
            }
            
        ThisIsGenerateKey.setText(testwork4.Generate.Key(intlengthKey, intcomplicatedKey));
    }//GEN-LAST:event_StartGenerateActionPerformed

    private void ButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ButtonExitActionPerformed

    private void ButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConfirmActionPerformed
        // EnterLine
        String line = EnterLine.getText();
        output_encoding_Base64.setText(testwork4.HandlerKey.encodedKeyBase64(line));
        output_encrypt_sha1.setText(testwork4.PasswordEncrypter.getProtectedKeySHA_1(line));
        output_encrypt_md5.setText(testwork4.PasswordEncrypter.getProtectedKeyMD_5(line));
        output_ecodingBase64_sha1.setText(testwork4.PasswordEncrypter.bufferKey2(testwork4.PasswordEncrypter.getProtectedKeySHA_1(line), "sha-1"));
        output_encodingBase64_md5.setText(testwork4.PasswordEncrypter.bufferKey2(testwork4.PasswordEncrypter.getProtectedKeyMD_5(line), "md5"));
    }//GEN-LAST:event_ButtonConfirmActionPerformed

    private void ButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResetActionPerformed
        EnterLine.setText(null);
        output_encoding_Base64.setText(null);
        output_encrypt_sha1.setText(null);
        output_encrypt_md5.setText(null);
        output_ecodingBase64_sha1.setText(null);
        output_encodingBase64_md5.setText(null);
    }//GEN-LAST:event_ButtonResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonConfirm;
    private javax.swing.JButton ButtonExit;
    private javax.swing.JButton ButtonReset;
    private javax.swing.JLabel ComplicatedKey;
    private javax.swing.JTextField EnterLine;
    private javax.swing.JLabel GeneratedKey;
    private javax.swing.JLabel LengthKey;
    private javax.swing.JLabel Line;
    private javax.swing.JButton StartGenerate;
    private javax.swing.JTextField ThisIsGenerateKey;
    private javax.swing.JTextField enterComplicatedKey;
    private javax.swing.JTextField enterLegthKey;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel nameProgramm;
    private javax.swing.JTextField output_ecodingBase64_sha1;
    private javax.swing.JTextField output_encodingBase64_md5;
    private javax.swing.JTextField output_encoding_Base64;
    private javax.swing.JTextField output_encrypt_md5;
    private javax.swing.JTextField output_encrypt_sha1;
    // End of variables declaration//GEN-END:variables
}
